### ISSUE TITLE
ERROR: 'FailAid/Extension' extension file or class could not be located. 

### ISSUE THREAD

**Issue by gnashty85** [forceedge01/behat-fail-aid#10]
What is the issue?
Tried to implement following instructions and am getting this error:
![image](https://user-images.githubusercontent.com/48029283/59298180-cdcaed00-8c3e-11e9-8dc4-370d6cc31eb1.png)

How did it happen?
You tell me.

What should have happened?
I should have gotten a screenshot.

![image](https://user-images.githubusercontent.com/48029283/59298295-17b3d300-8c3f-11e9-9981-0cd7de82cdbe.png)
I attempted to install the extension but keep getting the error above. I don't know if I am missing a dependency but I have never had any issues before. Thanks in advance.

- [ ] Demo

**Comment by forceedge01** [comment]
Thanks for logging the issue @gnashty85 , the above issue suggests an autoloading error. I've noticed you've got a forward slash in 'FailAid/Extension' rather than a backslash. Can you please update your extensions section to have 'FailAid\Extension' instead and let me know if that resolves the issue?

**Comment by forceedge01** [comment]
I suspect the above was indeed the issue you had, if you're facing any other issues please let me know. I will close this issue for now. Thanks for reporting.
